### ISSUE TITLE
Binary release on github

### ISSUE THREAD

**Issue by skomski** [NtQuery/Scylla#33]
It would be great if you could attach the binary to the release on github.
Currently only possible to download from official places where you need to register.

**Comment by tathanhdinh** [comment]
I have successfully compiled Scylla using VS2015, you can see a [64 bit build](https://github.com/NtQuery/Scylla/files/168339/x64.zip)

**Comment by Ceiridge** [comment]
# 

> [`**__**`](

- 

- [ ] 

- 

1. url

)

**Comment by NtQuery** [comment]
i will keep this in mind, thanks

**Comment by viki3d** [comment]
Yes, it is very annoying that binary is not available. Why need to install Visual Studio to compile Scylla instead just download it??? I wasted some time to compile last Scylla (v0.11). Hope to save time for others. Download it [here](http://download.viki3d.com/download/scylla/Scylla_v0.11.zip).
